name: Build and Deploy to Hostinger

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci --no-audit --no-fund

      - name: Build
        run: |
          npm run build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.TS_FTP_HOST || secrets.EI_FTP_SERVER || secrets.FTP_SERVER }}
          username: ${{ secrets.TS_FTP_USERNAME || secrets.EI_FTP_USERNAME || secrets.FTP_USERNAME }}
          password: ${{ secrets.TS_FTP_PASSWORD || secrets.EI_FTP_PASSWORD || secrets.FTP_PASSWORD }}
          protocol: ftps
          local-dir: dist/
          server-dir: ${{ secrets.TS_FTP_DIR || secrets.EI_FTP_SERVER_DIR || secrets.FTP_SERVER_DIR }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.astro/**
            **/.github/**
            **/README*
