name: End-to-End Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
      E2E_BASE_URL: http://127.0.0.1:4321
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Build Astro site
        run: npm run build

      - name: Start Astro preview
        run: |
          npx astro preview --host 0.0.0.0 --port 4321 &
          PREVIEW_PID=$!
          echo "PREVIEW_PID=$PREVIEW_PID" >> $GITHUB_ENV

      - name: Wait for preview to be ready
        run: npx wait-on@latest --timeout 60000 http://127.0.0.1:4321

      - name: Run Playwright+Cucumber tests
        run: npm run test:e2e

      - name: Stop Astro preview
        if: always()
        run: |
          if [ -n "$PREVIEW_PID" ]; then
            kill $PREVIEW_PID || true
          fi

      - name: Upload Cucumber HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html
          path: reports/cucumber.html
          if-no-files-found: warn

      - name: Upload Playwright traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: artifacts/traces
          if-no-files-found: ignore
